### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [Lani/fampi#1]
bad API use: https://github.com/Lani/fampi/blob/c733978ad7b6fe9a43604fb8b26dc77640770dff/src/server/users/userModel.js#L14

Instead, use [oneOrNone](http://vitaly-t.github.io/pg-promise/Database.html#.oneOrNone), and check the result for `null` ;)

**Comment by Lani** [comment]
Will do! Thanks for the feedback! That's much better, thanks! :)
